---
title: "Derivation of time-independent growth functions"
author: "R. Molowny-Horas"
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{enumerate}
output:
  html_document: default
  pdf_document: default
  word_document: default
vignette: >
  %\VignetteIndexEntry{Derivation of time-independent growth functions}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

<br>
<br>

### Introduction

Growth, understood as the increase of the physical dimensions of an organism, characterizes the temporal evolution of many living entities better than many other features. By physical dimensions or size, terms that will be used indistinctly hereafter, we mean quantities that are directly related to the spatial space occupied by an organism (e.g. diameter and height for trees, or weight for mammals). As a matter of fact, size is usually easier to determine experimentally than age. Only under controlled conditions in a laboratory or field experiment can we manipulate variables that are directly related to age (e.g. seed germination). However, in natural experiments like e.g. forest inventories, observers do not have control over experimental conditions and, therefore, the age of an individual is seldom precisely quantifiable.

Even under ideal conditions, growth is hampered by structural and physiologically constraints, which set in as an organism gets larger. Those constraints make its growth rate (i.e. increment in size per unit time) to slow down beyond some point, approaching zero as time tends to infinite. We will hereby discard those cases in which growth in size may stop or even reverse (i.e. size reduction) due to, for example, worsening environmental conditions or fiercer competition. Therefore, it may seem reasonable to assume that, for an organism, there is an upper limit which is only reached under the most optimum climatic and environmental conditions. That upper limit is usually unknown but may be guessed by extrapolating observed trends. In addition, the upper limit assumption suggests that sigmoid-like curves may be a good analytical model to describe size as a function of time.

We will concern ourselves only with those cases where size increases monotonically with time. Thus, we will look for continuous and differentiable sigmoid curves, characterized by a regime of approximately linear growth followed by a gentle bend towards an upper asymptote. Let $y(t)$ be such a sigmoid curve, which depends on time or age $t$. Then, we can define growth simply as:

\begin{equation}
y(t_{2})-y(t_{1})=g\left(t_{1}, t_{2}\right)
\end{equation}

where $t_{1}<t_{2}$. Expressed this way, the new growth function $g\left(t_{1}, t_{2}\right)$ may often be difficult to apply since it depends on absolute age/time, which is usually an unknown quantity in natural experiments. Rather, we seek to express growth as a function of the time difference between observations, $\Delta=t_{2}-t_{1}$, a relative quantity that is much easier to obtain. That is, we want to write instead:

\begin{equation}
y(t_{2})-y(t_{1})=g\left(\Delta\right)
\end{equation}

Below we will derive time-independent (also known as age-independent) curves for several growth $g\left(\Delta\right)$ functions. These curves have all been derived from sigmoid age-dependent size curves, which implies that there is always an asymptotic maximum size, denoted as $A$ in all cases. Some curves are well-known and widely used (e.g. logistic, Schumacher, Gompertz, monomolecular) whereas others are more rarely employed (e.g. arctangent, hyperbolic tangent). The dependence of growth on explanatory variables like e.g. climate, landscape structure, competition, etc. is conveyed through a growth rate parameter $k$, which is defined as a coefficient that directly multiplies age/time $t$. The existence of an explicit expression for the growth rate parameter $k$ has been a further requirement in developing those growth curves. In addition, we have allowed for a term $B$ which accounts for an (a priori unknown) offset in the growth curve. Nevertheless, as we will see below, this summative offset $B$ conveniently vanishes in all cases when $g$ or $k$ are expressed as a function of $\Delta$. Finally, $g\left(\Delta\right)=0$ when $\Delta=0$ or $k=0$ in all cases, as assumed.

<br>

#### Logistic growth function

The logistic curve is one of the most widely used functions to determine the growth of an individual plant or animal. In a general case, in which size depends on time $t$ as well as on a set of predictors (e.g. climatic, topographic), the size $y$ of an organism that obeys the logistic rule can be written:

\begin{equation}
  y=\frac{A}{1+e^{-\left(k\cdot t+B\right)}}
\end{equation}

To obtain a time-independent growth equation that determines growth between two time points $t_{1}$ and $t_{2}$, $t_{1}<t_{2}$, we start by writing:

\begin{equation}
  e^{-\left(k\cdot t+B\right)}=\frac{A}{y}-1
\end{equation}

\begin{equation}
  t=\frac{1}{k}\cdot \ln\left(\frac{A-y}{y}-B\right)
\end{equation}

Let us define a subscript notation whereby $t_{1}$ and $t_{2}$ indicate time points separated by $\Delta$ years, where $\Delta=t_{2}-t_{1}$. Likewise, $y_{1}$ and $y_{2}$ will denote sizes at those time points, respectively. Then:

\begin{equation}
\Delta =t_{2}-t_{1}=\frac{1}{k}\cdot\left[\ln\left(\frac{y_{2}}{y_{1}}\cdot\frac{A-y_{1}}{A-y_{2}}\right)\right]
\end{equation}

The $B$ coefficient has conveniently disappeared from the equation. Now we can easily deduce the following expression for $k$:

\begin{equation}
  k=\frac{1}{\Delta}\cdot\left[\ln\left(\frac{y_{2}}{y_{1}}\cdot\frac{A-y_{1}}{A-y_{2}}\right)\right]
\end{equation}

Since $t_{2}=t_{1}+\Delta$, we can arrive at an expression for $y_{2}$ as a function of $y_{1}$, $\Delta$ and the coefficients $a_{i}$:

\begin{equation}
  y_{2}=\frac{A}{1+e^{-\left(k\cdot t_{1}+B\right)}\cdot e^{-k\cdot\Delta}}=\frac{A}{1+\left(\frac{A}{y_{1}}-1\right)\cdot e^{-k\cdot\Delta}}
\end{equation}

Finally, growth can be expressed as:

\begin{equation}
  g\left(\Delta\right)=\frac{A}{1+e^{-\left(k\cdot t_{1}+B\right)}\cdot e^{-k\cdot\Delta}}=\frac{A}{1+\left(\frac{A}{y_{1}}-1\right)\cdot e^{-k\cdot\Delta}}-y_{1}
\end{equation}

<br>

#### Schumacher growth function

The Schumacher growth curve can be expressed as:

\begin{equation}
  y=A\cdot e^{-\frac{1}{k\cdot t+B}}
\end{equation}

For this curve to make ecological sense, $k\cdot t+B>0$ always. Then, we can express $t$ as:

\begin{equation}
  t=\frac{1}{k}\cdot\frac{1}{\ln\left(\frac{A}{y}\right)}-\frac{1}{k}\cdot B
\end{equation}

Now, following the same notation as shown above, we write:

\begin{equation}
  \Delta=\frac{1}{k}\cdot\left[\frac{1}{\ln\left(\frac{A}{y_{2}}\right)}-\frac{1}{\ln\left(\frac{A}{y_{1}}\right)}\right]
\end{equation}

As above, the offset $B$ has vanished from the equation. Then:

\begin{equation}
  k=\frac{1}{\Delta}\cdot\left[\frac{1}{\ln\left(\frac{A}{y_{2}}\right)}-\frac{1}{\ln\left(\frac{A}{y_{1}}\right)}\right]
\end{equation}

Therefore:

\begin{equation}
  y_{2}=A\cdot e^{-\left[\frac{1}{\frac{1}{\ln\left(\frac{A}{y_{1}}\right)}+k\cdot\Delta}\right]}
\end{equation}

This is exactly Equation [9] in Tomé et al. (2006), Canadian Journal of Forest Research.

<br>


#### Gompertz growth function

\begin{equation}
  y=A\cdot e^{-e^{-\left(k\cdot t+B\right)}}
\end {equation}

B is an offset.

\begin{equation}
  t=\frac{1}{k}\cdot\left[\ln\left(\frac{1}{\ln\left(\frac{A}{y}\right)}\right)-B\right]
\end{equation}


\begin{equation}
  \Delta=\frac{1}{k}\cdot\ln\left(\frac{\ln\left(\frac{A}{y_{1}}\right)}{\ln\left(\frac{A}{y_{2}}\right)}\right)
\end{equation}


\begin{equation}
  k=\frac{1}{\Delta}\cdot\ln\left(\frac{\ln\left(\frac{A}{y_{1}}\right)}{\ln\left(\frac{A}{y_{2}}\right)}\right)
\end{equation}

\begin{equation}
  y_{2}=A\cdot\left(\frac{y_{1}}{A}\right)^{e^{-k\cdot\Delta}}
\end{equation}


<br>

#### Monomolecular growth function

\begin{equation}
  y=A\cdot \left(1-e^{-\left( k\cdot t+B\right)}\right)
\end {equation}


\begin{equation}
  t=\frac{1}{k}\cdot \left[\ln\left(\frac{A}{A-y}\right)-B\right]
\end {equation}

\begin{equation}
  \Delta=\frac{1}{k}\cdot \left[\ln\left(\frac{A-y_{1}}{A-y_{2}}\right)\right]
\end {equation}

\begin{equation}
  k=\frac{1}{\Delta}\cdot \left[\ln\left(\frac{A-y_{1}}{A-y_{2}}\right)\right]
\end {equation}

\begin{equation}
  y_{2}=A-\left(A-y_{1}\right)\cdot e^{-k\cdot \Delta}
\end {equation}

<br>

#### Arctangent growth function

The arctangent is another sigmoid curve from which a time-independent growth function can be derived relatively easily. We start by expressing growth as a function of time:

\begin{equation}
  y=A\cdot \left(\frac{1}{\pi}\cdot \arctan\left(k\cdot t+B\right)+0.5\right)
\end {equation}

Thus, growth $y\in \left[0,A\right]$ and $B$ has been included to allow for any possible offset in the curve. We can easily get:

\begin{equation}
  k\cdot t=\tan\left[\left(\frac{y}{A}-0.5\right)\cdot\pi\right]-B
\end{equation}

Therefore:

\begin{equation}
  t=\frac{1}{k}\cdot\tan\left[\left(\frac{y}{A}-0.5\right)\cdot\pi\right]-B
\end{equation}


\begin{equation}
  \Delta=\frac{1}{k}\cdot\left[\tan\left(\left(\frac{y_{2}}{A}-0.5\right)\cdot\pi\right)-\tan\left(\left(\frac{y_{1}}{A}-0.5\right)\cdot\pi\right)\right]
\end{equation}

Thus, the offset term $B$ has vanished from the equation. An equivalent expression for $k$ is:

\begin{equation}
  k=\frac{1}{\Delta}\cdot\left[\tan\left(\left(\frac{y_{2}}{A}-0.5\right)\cdot\pi\right)-\tan\left(\left(\frac{y_{1}}{A}-0.5\right)\cdot\pi\right)\right]
\end{equation}


Finally, we derive:

\begin{equation}
\tan\left(\left(\frac{y_{2}}{A}-0.5\right)\cdot\pi\right)=\tan\left(\left(\frac{y_{1}}{A}-0.5\right)\cdot\pi\right)+k\cdot\Delta
\end{equation}

and then:
\begin{equation}
y_{2}=A\cdot\left[\frac{1}{\pi}\cdot \arctan\left\{\tan\left(\left(\frac{y_{1}}{A}-0.5\right)\cdot\pi\right)+k\Delta\right\}+0.5\right]
\end{equation}

<br>

#### Hyperbolic tangent growth function

\begin{equation}
  y=\frac{A}{2}\cdot\left[\tanh\left(k\cdot t+B\right)+1\right]=\frac{A}{2}\cdot\frac{e^{2\cdot\left(k\cdot t+B\right)}-1}{e^{2\cdot\left(k\cdot t+B\right)}+1}=
    A\cdot\frac{e^{2\cdot k\cdot t}}{e^{2\cdot k\cdot t}+e^{-2\cdot B}}
\end{equation}


\begin{equation}
  e^{2\cdot k\cdot t}=\frac{y}{A-y}\cdot e^{-2\cdot B}
\end {equation}


\begin{equation}
  t=\frac{1}{2\cdot k}\cdot\left[\ln\left(\frac{y}{A-y}\right)-2\cdot B\right]
\end{equation}

\begin{equation}
  \Delta=\frac{1}{2\cdot k}\cdot\ln\left(\frac{y_{2}}{y_{1}}\cdot\frac{A-y_{1}}{A-y_{2}}\right)
\end{equation}

\begin{equation}
  k=\frac{1}{2\cdot\Delta}\cdot\ln\left(\frac{y_{2}}{y_{1}}\cdot\frac{A-y_{1}}{A-y_{2}}\right)
\end{equation}

Since $t_{2}=t_{1}+\Delta$:

\begin{equation}
  y_{2}=A\cdot\frac{e^{2\cdot k\cdot t_{1}}\cdot e^{2\cdot k\cdot\Delta}}{e^{2\cdot k\cdot t_{1}}\cdot e^{2\cdot k\cdot\Delta}+e^{-2\cdot B}}
\end{equation}

Thus:

\begin{equation}
  y_{2}=A\cdot\frac{\frac{y_{1}}{A-y_{1}}\cdot e^{2\cdot k\cdot\Delta}}{\frac{y_{1}}{A-y_{1}}\cdot e^{2\cdot k\cdot\Delta}+1}
\end{equation}

Finally:

\begin{equation}
  y_{2}=A\cdot\frac{y_{1}}{y_{1}+\left({A-y_{1}}\right)\cdot e^{-2\cdot k\cdot\Delta}}
\end{equation}

<br>

#### Growth rate parameter

We assume that the dependence of the growth rate parameter on a given set of predictors $X_{i}$ is linear. Then, $k$ can then be expressed as:

\begin{equation}
  k=\sum_{i=1}^{n} a_{i}\cdot X_{i}
\end{equation}

where the coefficients $a_{i}$ are unknown and must be calculated. There are cases where we wish to impose a strict positivity on $k$. At the same time, we prefer an expression that does not lead to unrealistically high values for $k$. Examples of this behaviour may come about, for example, when computing projections for $X_{i}$ values that are very different from the ones used during calibration. In those instances, we can force $k$ to be strictly positive by expressing it as a logistic function of the variables $X_{i}$. In this case, we replace the lineal expression from above with the following:

\begin{equation}
k=\frac{C}{1+e^{-\sum_{i=1}^{n} a_{i}\cdot X_{i}}}
\end{equation}

A new transformation is thus needed to obtain a linear expression. After some algebra, we get:

\begin{equation}
\sum_{i=1}^{n} a_{i}\cdot X_{i}=\ln\left(\frac{k}{k_{max}-k}\right)
\end{equation}

Using a logistic function for $k$ has the advantage of not letting $k$ reach absurdly low or high values, since $k\in \left[0,C\right]$ always. A new parameter $k_{max}$ is, however, necessary to set an upper limit to $k$.

