---
title: "Regression of time-independent growth equations"
author: "Roberto Molowny-Horas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The time-independent growth equations described in this package are intrinsically nonlinear in the $k$ parameter. Regressing growth $y_{2}-y_{1}$ against a linear function of a set of parameters through the $k$ parameter may quickly become problematic. Non-linear regressions usually require a good set of initial parameters for the algorithm to converge to a global minimum, lest we end up in a local minimum or without convergence at all. Therefore, guaranteeing convergence implies finding a good set of starting values to feed the regression function.


The obvious non-linearity of the time-independent equations below makes it challenging to devise a regression scheme with which to fit those expressions to a set of observational data. Good starting guesses for the parameters of the fit become a key ingredient for a quick and satisfactory convergence of the regression algorithms. Otherwise, those algorithms may fail to converge, or do so to a local, rather than global, extreme. Therefore, we have extracted simple expressions for the so-called growth rate parameter $k$, which can be fitted in an initial step as linear expressions of the predictors. The coefficients thus calculated can then be used as first guesses for the full non-linear regression to the time-independent growth curves.
