---
title: "Regression of time-independent growth equations"
author: "Roberto Molowny-Horas"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Introduction

Tree growth curves are graphical representations of the changes over time in diameter, height, volume, etc. of an individual tree. For most trees those changes are monotonically increasing and usually follow a characteristic sigmoid pattern, where we can distinguish three main phases:

* Slow initial growth: growth is relatively slow at this stage
* Rapid growth: as the tree matures, its annual growth typically increases.
* Mature and senescent growth: as the tree ages, its annual growth typically slows down, and declines further in the senescent phase.

Tree growth depends on different factors like e.g. species, site quality (for instance, soil composition and texture, soil depth and water-holding capacity), topography, climate, intra or interspecies competition, management practices, disturbances, etc. The exact functional dependence of tree growth on these and other factors is usually unknown, or very hard to derive from e.g. process-based models. 

Thus, in this work tree growth will not be determined theoretical from a physiological model. Rather, we will infer tree growth by means of a regression-based model in which a given relationship, usually non-linear, is assumed between tree growth and a set of factors or predictors. However, to be able to simplify our non-linear regression approach further, we will look for sigmoid functions where time $t$ is multiplied by a single term $k$ (that is, $k\cdot t$) which, from now on, we will define as **growth rate**. It is through this term $k$ that we will convey the dependence of tree growth on those growth factors.


### Growth rate parameter

We assume that the dependence of the growth rate parameter $k$ on a given set of factors $X_{i}$ is linear. Then, $k$ can then be expressed simply as:

\begin{equation}
  k=\sum_{i=1}^{n} a_{i}\cdot X_{i}
\end{equation}

where the coefficients $a_{i}$ are unknown and must be calculated.

There are cases where we wish to constrain $k$ to be strictly positive. At the same time, we may seek an expression that does not lead to nonsensical high values for $k$. Examples of this behavior may come about, for example, when computing projections for $X_{i}$ values that are very different from the ones used during calibration. To prevent the equations from calculating unrealistic $k$ values, we can force $k$ to be strictly positive and with an upper bound by expressing it as a logistic function of the variables $X_{i}$. In this case, we replace the lineal expression from above with the following:

\begin{equation}
k=\frac{k_{max}}{1+e^{-\sum_{i=1}^{n} a_{i}\cdot X_{i}}}
\end{equation}

A new transformation is thus needed to obtain a linear expression. After some algebra, we get:

\begin{equation}
\sum_{i=1}^{n} a_{i}\cdot X_{i}=\ln\left(\frac{k}{k_{max}-k}\right)
\end{equation}

Using a logistic function for $k$ has the advantage of not letting $k$ reach absurdly low or high values, since $k\in \left[0,k_{max}\right]$ always. A new parameter $k_{max}$ is, however, necessary to set an upper limit to $k$.

The time-independent growth equations described in this package are intrinsically nonlinear in the $k$ parameter. Those sigmoid equations describe size $y(t, k)$ as a function of $t$ and $k$. However, it is more convenient to regress growth (i.e. size change $y(t_{2}, k)-y(t_{1}, k))$ between two time points $t_{1}$ and $t_{2}$, with $t_{1}<$t_{2}$), rather than absolute size because it allows us to write down the new sigmoid function in a more streamlined way. It also eliminates the direct dependence on absolute time $t$ because the new equations are now functions of a time interval $\Delta = t_{2}-t_{1}$ (see Vignette for details).

Regressing growth $y_{2}$ vs, $y_{1}$ against a linear function of a set of parameters through the $k$ parameter may quickly become problematic. Non-linear regressions usually require a good set of initial parameters for the algorithm to converge to a global minimum, lest we end up in a local minimum or without convergence at all. Therefore, guaranteeing convergence implies finding a good set of starting values to feed the regression function.


The obvious non-linearity of the time-independent equations below makes it challenging to devise a regression scheme with which to fit those expressions to a set of observational data. Good starting guesses for the parameters of the fit become a key ingredient for a quick and satisfactory convergence of the regression algorithms. Otherwise, those algorithms may fail to converge, or do so to a local, rather than global, extreme. Therefore, we have extracted simple expressions for the so-called growth rate parameter $k$, which can be fitted in an initial step as linear expressions of the predictors. The coefficients thus calculated can then be used as first guesses for the full non-linear regression to the time-independent growth curves.


### Regression algorithm implementation


